project_id = "lindio"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 55323
api_url = "http://127.0.0.1"

[local_smtp]
enabled = true
port = 55324
smtp_port = 55325
pop3_port = 55326

[analytics]
enabled = false
port = 55327
vector_port = 55328
backend = "postgres"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://127.0.0.1:5173", "http://localhost:5173/reset-password", "http://127.0.0.1:5173/reset-password"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
